<?php

//create database copy to query phpmyadmin
CREATE TABLE SELLER (
	SEL_ID CHAR(6) NOT NULL UNIQUE,
	SEL_NAME VARCHAR(50) NOT NULL,
	SEL_TEL VARCHAR(10) NOT NULL,
	SEL_ADDRESS VARCHAR(100) NOT NULL,
	SEL_DESCRIPT VARCHAR(200) NOT NULL,
	PRIMARY KEY (SEL_ID)
);

CREATE TABLE PRODUCT (
	PRO_ID CHAR(6) NOT NULL UNIQUE,
	SEL_ID CHAR(6) NOT NULL,
	PRO_NAME VARCHAR(50) NOT NULL,
	PRO_SELLPRICE INT NOT NULL,
	PRO_BUYPRICE INT NOT NULL,
	PRO_AMOUNT INT NOT NULL,
	PRO_WAMOUNT INT NOT NULL,
	PRO_DETAIL VARCHAR(200) NOT NULL,
	PRIMARY KEY (PRO_ID),
	FOREIGN KEY (SEL_ID) REFERENCES SELLER(SEL_ID)
);

CREATE TABLE ORDERS (
	ORD_ID CHAR(10) NOT NULL UNIQUE,
	SEL_ID CHAR(6) NOT NULL,
	ORD_DATE DATE NOT NULL,
	ORD_GETDATE DATE NOT NULL,
	ORD_PAYDATE DATE NOT NULL,
	ORD_TOTALPRICE INT NOT NULL,
	ORD_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (ORD_ID),
	FOREIGN KEY (SEL_ID) REFERENCES SELLER(SEL_ID)
);

CREATE TABLE ORDER_DETAIL (
	ORDD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	ORD_ID CHAR(10) NOT NULL,
	ORDD_AMOUNT INT NOT NULL,
	ORDD_TOTALPRICE INT NOT NULL,
	ORDD_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (ORDD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);

CREATE TABLE GET_PRODUCT_ORDER (
	GPO_ID CHAR(10) NOT NULL UNIQUE,
	ORD_ID CHAR(10) NOT NULL,
	GPO_DATE DATE NOT NULL,
	GPO_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (GPO_ID),
	FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);

CREATE TABLE GET_PRODUCT_ORDER_DETAIL (
	GPOD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	GPO_ID CHAR(10) NOT NULL,
	ORDD_NUMBER INT NOT NULL,
	GPOD_GETAMOUNT INT NOT NULL,
	PRIMARY KEY (GPOD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (GPO_ID) REFERENCES GET_PRODUCT_ORDER(GPO_ID),
	FOREIGN KEY (ORDD_NUMBER) REFERENCES ORDER_DETAIL(ORDD_NUMBER)
);

CREATE TABLE CLAIMSLIP_ORDER (
	CLO_ID CHAR(10) NOT NULL UNIQUE,
	ORD_ID CHAR(10) NOT NULL,
	CLO_DATE DATE NOT NULL,
	CLO_GETDATE DATE NOT NULL,
	CLO_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (CLO_ID),
	FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);

CREATE TABLE CLAIM_ORDER_DETAIL (
	CLAD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	CLO_ID CHAR(10)	NOT NULL,
	CLAD_AMOUNT INT NOT NULL,
	CLAD_DESCRIPT VARCHAR(200) NOT NULL,
	CLAD_STATUS CHAR(1) NOT NULL,
	ORDD_NUMBER INT NOT NULL,
	PRIMARY KEY (CLAD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (CLO_ID) REFERENCES CLAIMSLIP_ORDER(CLO_ID)
);

CREATE TABLE GET_PRODUCT_CLAIM_ORDER (
	GPCO_ID CHAR(10) NOT NULL UNIQUE,
	CLO_ID CHAR(10) NOT NULL,
	GPCO_DATE DATE NOT NULL,
	GPCO_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (GPCO_ID),
	FOREIGN KEY (CLO_ID) REFERENCES CLAIMSLIP_ORDER(CLO_ID)
);

CREATE TABLE GET_PRODUCT_CLAIM_ORDER_DETAIL (
	GPCOD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	GPCO_ID CHAR(10) NOT NULL,
	CLAD_NUMBER INT NOT NULL,
	GPCOD_GETAMOUNT INT NOT NULL,
	PRIMARY KEY (GPCOD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (GPCO_ID) REFERENCES GET_PRODUCT_CLAIM_ORDER(GPCO_ID),
	FOREIGN KEY (CLAD_NUMBER) REFERENCES CLAIM_ORDER_DETAIL(CLAD_NUMBER)
);

CREATE TABLE EMPLOYEE (
	EMP_ID CHAR(6) NOT NULL UNIQUE,
	EMP_FNAME VARCHAR(30) NOT NULL,
	EMP_LNAME VARCHAR(30) NOT NULL,
	EMP_GENDER CHAR(1) NOT NULL,
	EMP_TEL CHAR(10) NOT NULL,
	EMP_ADDRESS VARCHAR(100) NOT NULL,
	EMP_DATE_BEGINWORK DATE NOT NULL,
	EMP_SALARY INT NOT NULL,
	EMP_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (EMP_ID)
);

CREATE TABLE SCHEDULE (
	SCH_ID CHAR(10) NOT NULL UNIQUE,
	EMP_ID CHAR(6) NOT NULL,
	SCH_DATE DATE NOT NULL,
	SCH_STARTTIME TIME NOT NULL,
	SCH_FINISHTIME TIME NOT NULL,
	SCH_AMOUNTHOUR SMALLINT NOT NULL,
	PRIMARY KEY (SCH_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

CREATE TABLE SALARY (
	SAL_ID CHAR(10) NOT NULL UNIQUE,
	EMP_ID CHAR(6) NOT NULL,
	SAL_SALARY INT NOT NULL,
	SAL_FINE INT NOT NULL,
	SAL_NETSALARY INT NOT NULL,
	SAL_PAYDATE DATE NOT NULL,
	SAL_PAYROUNDDATE VARCHAR(50) NOT NULL,
	PRIMARY KEY(SAL_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

CREATE TABLE TAKEDAYOFF (
	TAK_ID CHAR(10) NOT NULL UNIQUE,
	EMP_ID CHAR(6) NOT NULL,
	TAK_DATEBEGIN DATE NOT NULL,
	TAK_DATEEND DATE NOT NULL,
	TAK_AMOUNTHOUR SMALLINT NOT NULL,
	PRIMARY KEY (TAK_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

CREATE TABLE CUSTOMER (
	CUS_ID CHAR(13) NOT NULL UNIQUE,
	CUS_FNAME VARCHAR(30) NOT NULL,
	CUS_LNAME VARCHAR(30) NOT NULL,
	CUS_TEL CHAR(10) NOT NULL,
	CUS_ADDRESS VARCHAR(100) NOT NULL,
	PRIMARY KEY (CUS_ID)
);

CREATE TABLE CARS (
    	CAR_VIN CHAR(17) NOT NULL UNIQUE,
    	CAR_ENGINE_ID VARCHAR(30) NOT NULL,
	CAR_LICENSE VARCHAR(10)	NOT NULL,
	CUS_ID CHAR(10) NOT NULL,
	CAR_PROVINCE VARCHAR(50) NOT NULL,
	CAR_BRAND VARCHAR(50) NOT NULL,
	CAR_MODEL VARCHAR(50) NOT NULL,
	CAR_COLOR VARCHAR(30) NOT NULL,
	PRIMARY KEY (CAR_VIN),
	FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE TABLE BUYSLIP (
	BUY_ID CHAR(10) NOT NULL UNIQUE,
	BUY_DATE DATE NOT NULL,
	BUY_TOTALPRICE INT NOT NULL,
	PRIMARY KEY (BUY_ID)
);

CREATE TABLE BUYSLIP_DETAIL (
	BUYD_NUMBER INT NOT NULL UNIQUE,
	BUY_ID CHAR(10) NOT NULL,
	PRO_ID CHAR(6) NOT NULL,
	BUYD_AMOUNT INT NOT NULL,
	BUYD_TOTALPRICE INT NOT NULL,
	PRIMARY KEY (BUYD_NUMBER),
	FOREIGN KEY (BUY_ID) REFERENCES BUYSLIP(BUY_ID),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID)
);

CREATE TABLE CLAIMSLIP_BUY (
	CLB_ID CHAR(10) NOT NULL UNIQUE,
	BUY_ID CHAR(10) NOT NULL,
	CLB_DATE DATE NOT NULL,
	CLB_GETDATE DATE NOT NULL,
	CLB_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (CLB_ID),
	FOREIGN KEY (BUY_ID) REFERENCES BUYSLIP(BUY_ID)
);

CREATE TABLE CLAIM_BUY_DETAIL (
	CLBD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	CLB_ID CHAR(10) NOT NULL,
	BUYD_NUMBER INT NOT NULL,
	CLBD_AMOUNT INT NOT NULL,
	CLBD_DESCRIPT VARCHAR(100) NOT NULL,
	CLBD_STATUS CHAR(1) NOT NULL,
	PRIMARY KEY (CLBD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (CLB_ID) REFERENCES CLAIMSLIP_BUY(CLB_ID),
	FOREIGN KEY (BUYD_NUMBER) REFERENCES BUYSLIP_DETAIL(BUYD_NUMBER)
);

CREATE TABLE GET_PRODUCT_CLAIM_BUY (
	GPCB_ID CHAR(10) NOT NULL UNIQUE,
	CLB_ID CHAR(10) NOT NULL,
	GPCB_DATE DATE NOT NULL,
	GPCB_STATUS CHAR(1) NULL,
	PRIMARY KEY (GPCB_ID),
	FOREIGN KEY (CLB_ID) REFERENCES CLAIMSLIP_BUY(CLB_ID)
);

CREATE TABLE GET_PRODUCT_CLAIM_BUY_DETAIL (
	GPCBD_NUMBER INT NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	GPCB_ID CHAR(10) NOT NULL,
	CLBD_NUMBER INT NOT NULL,
	GPCBD_GETAMOUNT INT NOT NULL,
	PRIMARY KEY (GPCBD_NUMBER),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (GPCB_ID) REFERENCES GET_PRODUCT_CLAIM_BUY(GPCB_ID),
	FOREIGN KEY (CLBD_NUMBER) REFERENCES CLAIM_BUY_DETAIL(CLBD_NUMBER)
);

CREATE TABLE REPAIRSLIP (
	REP_ID CHAR(10) NOT NULL UNIQUE,
	CUS_ID CHAR(13) NOT NULL,
	CAR_VIN CHAR(17) NOT NULL,
	EMP_ID CHAR(6) NOT NULL,
	REP_DATE DATE NOT NULL,
	REP_DATE_GETCAR DATE NOT NULL,
	REP_TOTALCOST INT NOT NULL,
	REP_DETAIL VARCHAR(200) NOT NULL,
	REP_KILOMATER INT NOT NULL,
	REP_REPAIRSTATUS CHAR(1) NOT NULL,
	REP_PAYMENTSTATUS CHAR(1) NOT NULL,
	REP_NETTOTALCOST DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (REP_ID),
	FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
	FOREIGN KEY (CAR_VIN) REFERENCES CARS(CAR_VIN),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);


CREATE TABLE SERVICE (
	SER_ID CHAR(10) NOT NULL UNIQUE,
	SER_NAME VARCHAR(200) NOT NULL,
	SER_BEGINCOST INT NOT NULL,
	PRIMARY KEY (SER_ID)
);

CREATE TABLE SERVICE_DETAIL (
	SERD_NUMBER INT NOT NULL UNIQUE,
	SER_ID CHAR(10) NOT NULL,
	EMP_ID CHAR(6) NOT NULL,
	SERD_AMOUNT INT NOT NUlL,
	REP_ID CHAR(10) NOT NULL,
	SERD_COST INT NOT NULL,
	PRIMARY KEY (SERD_NUMBER),
	FOREIGN KEY (SER_ID) REFERENCES SERVICE(SER_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	FOREIGN KEY (REP_ID) REFERENCES REPAIRSLIP(REP_ID)
);

CREATE TABLE REQUISITION (
	REQ_NUMBER INT NOT NULL UNIQUE,
	REP_ID CHAR(10) NOT NULL,
	PRO_ID CHAR(6)	NOT NULL,
	REQ_AMOUNT INT NOT NULL,
	REQ_TOTALPRICE INT NOT NULL,
	PRIMARY KEY (REQ_NUMBER),
	FOREIGN KEY (REP_ID) REFERENCES REPAIRSLIP(REP_ID),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID)
);

CREATE TABLE INJURY (
	INJ_ID CHAR(10) NOT NULL UNIQUE,
	PRO_ID CHAR(6) NOT NULL,
	EMP_ID CHAR(6) NOT NULL,
	INJ_DESCRIPTION VARCHAR(100) NOT NULL,
	INJ_AMOUNT INT NOT NULL,
	INJ_COST INT NOT NULL,
	REP_ID CHAR(10) NOT NULL,
	INJ_DATE DATE NOT NULL,
	PRIMARY KEY (INJ_ID),
	FOREIGN KEY (PRO_ID) REFERENCES PRODUCT(PRO_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	FOREIGN KEY (REP_ID) REFERENCES REPAIRSLIP(REP_ID)
);

CREATE TABLE PAYMENT_ORDER (
	PAYO_ID CHAR(10) NOT NULL UNIQUE,
	ORD_ID CHAR(10) NOT NULL,
	PAYO_DATE DATE NOT NULL,
	PAYO_PRICE INT(11) NOT NULL,
	PRIMARY KEY (PAYO_ID),
	FOREIGN KEY (ORD_ID) REFERENCES ORDERS(ORD_ID)
);



 ?>
